import datetime
import subprocess

def create_version_file():
    try:
        filename = "version.h"
        
        with open(filename, 'w', encoding='utf-8') as file:
            t = datetime.datetime.now()
            datestring = t.strftime("%d-%b-%Y (%H:%M:%S)")
            version = subprocess.run('git describe --always --long --tags --dirty', stdout=subprocess.PIPE, shell=True, check=True)
            author = subprocess.run("git log -1 --pretty=format:\"%an\"", stdout=subprocess.PIPE, shell=True, check=True)

            file.write(f"// File automatically generated by createVersionHeader.py")
            file.write(f"\n// File created on: {datestring} \n")
            file.write(f"\n#pragma once")
            file.write(f"\n#define VERSION_INFO   \"{version.stdout.decode().strip()}\"")
            file.write(f"\n#define VERSION_AUTHOR \"{author.stdout.decode().strip().replace('.', ' ')}\"")
            file.write(f"\n#define VERSION_COMPILATION_DATE __date__")
            file.close()
            
    except (FileNotFoundError, subprocess.CalledProcessError) as e:
        print(f"Error creating version file: {str(e)}")

create_version_file()
